server:
  port: 8080

spring:
  application:
    name: usj-chat-app

  datasource:
    url: jdbc:postgresql://localhost:5432/usjchatapp
    username: ${DB_USERNAME:usjchatapp}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
      expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.usjchatapp: DEBUG
    org.springframework.security: DEBUG
