-- テストユーザーデータ
-- パスワード: password123 のBCryptハッシュ値
-- ON CONFLICTを使用して安全に挿入（重複時はスキップ）
-- テストユーザーを追加
-- password123 = $2a$10$TGiQfIiMCx2OcJi6nM23jupcWlDSGCAvW6vOFwpCwZJU/9jjkTF5u
INSERT INTO users (
        email,
        password,
        display_name,
        profile_image,
        bio,
        role,
        created_at,
        updated_at,
        is_active
    )
VALUES (
        'admin@example.com',
        '$2a$10$TGiQfIiMCx2OcJi6nM23jupcWlDSGCAvW6vOFwpCwZJU/9jjkTF5u',
        'システム管理者',
        null,
        'システム管理者です。お困りの際はお気軽にお声かけください。',
        'ADMIN',
        NOW(),
        NOW(),
        true
    ),
    (
        'alice@example.com',
        '$2a$10$TGiQfIiMCx2OcJi6nM23jupcWlDSGCAvW6vOFwpCwZJU/9jjkTF5u',
        'アリス',
        null,
        'チャットアプリを愛用しています！よろしくお願いします。',
        'USER',
        NOW(),
        NOW(),
        true
    ),
    (
        'bob@example.com',
        '$2a$10$TGiQfIiMCx2OcJi6nM23jupcWlDSGCAvW6vOFwpCwZJU/9jjkTF5u',
        'ボブ',
        null,
        'プログラミングとゲームが趣味です。',
        'USER',
        NOW(),
        NOW(),
        true
    ),
    (
        'charlie@example.com',
        '$2a$10$TGiQfIiMCx2OcJi6nM23jupcWlDSGCAvW6vOFwpCwZJU/9jjkTF5u',
        'チャーリー',
        null,
        '読書と映画鑑賞が好きです。おすすめがあれば教えてください！',
        'USER',
        NOW(),
        NOW(),
        true
    ),
    (
        'diana@example.com',
        '$2a$10$TGiQfIiMCx2OcJi6nM23jupcWlDSGCAvW6vOFwpCwZJU/9jjkTF5u',
        'ダイアナ',
        null,
        '旅行と写真撮影が趣味です。',
        'USER',
        NOW(),
        NOW(),
        true
    ),
    (
        'eve@example.com',
        '$2a$10$TGiQfIiMCx2OcJi6nM23jupcWlDSGCAvW6vOFwpCwZJU/9jjkTF5u',
        'イブ',
        null,
        '料理とお菓子作りが大好きです♪',
        'USER',
        NOW(),
        NOW(),
        true
    ),
    (
        'frank@example.com',
        '$2a$10$TGiQfIiMCx2OcJi6nM23jupcWlDSGCAvW6vOFwpCwZJU/9jjkTF5u',
        'フランク',
        null,
        'スポーツ観戦とアウトドアが好きです。',
        'USER',
        NOW(),
        NOW(),
        true
    ),
    (
        'grace@example.com',
        '$2a$10$TGiQfIiMCx2OcJi6nM23jupcWlDSGCAvW6vOFwpCwZJU/9jjkTF5u',
        'グレース',
        null,
        '音楽と絵画に興味があります。',
        'USER',
        NOW(),
        NOW(),
        true
    ) ON CONFLICT (email) DO NOTHING;